In [19]:
import mlflow
import pandas as pd
import matplotlib.pyplot as plt

import os
#os.environ["PATH"] = "/home/users/dmoreno2016/.TinyTeX/bin/x86_64-linux:" + os.environ["PATH"]

#plt.rcParams.update({
#    "text.usetex": True,
#    "pgf.texsystem": "pdflatex",
#    "font.family": "serif",
#    "font.serif": ["Palatino"],
#})


import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import classification_report

In [20]:
mlflow.set_tracking_uri("file:../models/ATAT/results/ml-runs")

In [21]:
data_name =  'ztf_ff'
experiment_name = f"classification/{data_name}/hp_tuning"

experiment = mlflow.get_experiment_by_name(experiment_name)
if experiment:
    experiment_id = experiment.experiment_id
    print(f"Experiment ID for '{experiment_name}': {experiment_id}")
else:
    print(f"Experiment '{experiment_name}' not found.")

runs = mlflow.search_runs(experiment_ids=[experiment_id])
runs = runs[
    (runs.status == 'FINISHED') & 
    (runs['metrics.mix/f1s_test/None_days'].notna())
    ]

display(runs.head())
print(f'{runs.shape}\n')

for col in runs.columns:
    print(col)

Experiment ID for 'classification/ztf_ff/hp_tuning': 745273885923147472

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.loss_test/1024_days/mix_ce,metrics.mix/rcl_test/None_days,metrics.loss_test/32_days/tab,metrics.loss_test/32_days/lc_ce,...,params.general/use_lightcurves_err,params.ft/embedding_size_sub,params.general/load_pretrained_model,params.lc/num_encoders,tags.mlflow.parentRunId,tags.mlflow.source.name,tags.mlflow.runName,tags.mlflow.source.type,tags.mlflow.user,tags.mlflow.source.git.commit
0,f46a3101b3fe435badd1e18d5d5880d5,745273885923147472,FINISHED,file:///home/dmoreno/pipeline_v4_final/pipelin...,2026-01-14 22:23:05.653000+00:00,2026-01-15 04:18:09.817000+00:00,0.372737,0.720646,0.584111,1.397838,...,True,512,False,4,d8a35e5502f54ae2a22ff5819e247067,training.py,Fold_4_2026-01-14_19-23-05,LOCAL,dmoreno2016,None
2,c5aed04a7df34c63afc04184625da973,745273885923147472,FINISHED,file:///home/dmoreno/pipeline_v4_final/pipelin...,2026-01-14 22:22:42.690000+00:00,2026-01-15 05:00:05.820000+00:00,0.407265,0.725628,0.616408,1.461842,...,True,512,False,4,61b69cda88e44ead8efed9cc867ad7b2,training.py,Fold_3_2026-01-14_19-22-42,LOCAL,dmoreno2016,None
4,66f68d85b4bf4ea38280701373aace94,745273885923147472,FINISHED,file:///home/dmoreno/pipeline_v4_final/pipelin...,2026-01-14 22:21:56.173000+00:00,2026-01-15 04:45:37.736000+00:00,0.369318,0.699501,0.573102,1.452454,...,True,256,False,4,1a418a29e8b84d16a0e7a9cc6c12cec5,training.py,Fold_4_2026-01-14_19-21-56,LOCAL,dmoreno2016,None
6,875f250a750e4967909d33fd480e2cd8,745273885923147472,FINISHED,file:///home/dmoreno/pipeline_v4_final/pipelin...,2026-01-14 22:21:30.242000+00:00,2026-01-15 05:34:00.842000+00:00,0.402615,0.712392,0.577974,1.435549,...,True,512,False,4,7e9a23d6fe5a4ac4adea43843ffdbc1f,training.py,Fold_2_2026-01-14_19-21-30,LOCAL,dmoreno2016,None
8,30cd423d063e4062b329fb48d85d369c,745273885923147472,FINISHED,file:///home/dmoreno/pipeline_v4_final/pipelin...,2026-01-14 03:33:04.388000+00:00,2026-01-14 11:45:52.916000+00:00,0.417882,0.687058,0.629673,1.467104,...,True,128,False,4,094f4bbef2494421a37a77c066630f5f,training.py,Fold_4_2026-01-13_11-03-02,LOCAL,dmoreno2016,None

(90, 214)

run_id
experiment_id
status
artifact_uri
start_time
end_time
metrics.loss_test/1024_days/mix_ce
metrics.mix/rcl_test/None_days
metrics.loss_test/32_days/tab
metrics.loss_test/32_days/lc_ce
metrics.loss_test/1024_days/mix_entropy
metrics.mix/rcl_valid
metrics.loss_test/1024_days/mix
metrics.loss_test/256_days/tab_ce
metrics.mix/f1s_test/None_days
metrics.mix/acc_test/512_days
metrics.loss_test/16_days/tab_entropy
metrics.loss_train/lc_ce
metrics.loss_test/512_days/mix_entropy
metrics.mix/acc_test/32_days
metrics.loss_test/128_days/total
metrics.loss_test/16_days/mix_ce
metrics.loss_test/512_days/tab
metrics.loss_test/32_days/lc_entropy
metrics.mix/rcl_test/64_days
metrics.loss_test/256_days/lc_entropy
metrics.loss_test/16_days/total
metrics.loss_test/128_days/tab
metrics.loss_test/32_days/mix_ce
metrics.loss_test/64_days/mix_ce
metrics.loss_test/16_days/tab_ce
metrics.loss_test/8_days/tab_ce
metrics.mix/acc_test/16_days
metrics.loss_test/128_days/mix
metrics.mix/rcl_test/1024_days
metrics.mix/f1s_test/64_days
metrics.loss_validation/mix
metrics.loss_train/mix_ce
metrics.loss_test/8_days/mix_entropy
metrics.mix/rcl_train_epoch
metrics.loss_test/512_days/tab_entropy
metrics.mix/rcl_test/8_days
metrics.loss_test/8_days/total
metrics.loss_test/128_days/mix_ce
metrics.loss_test/1024_days/lc_entropy
metrics.loss_test/1024_days/tab_entropy
metrics.mix/f1s_test/16_days
metrics.loss_validation/total
metrics.loss_test/32_days/lc
metrics.loss_test/8_days/mix_ce
metrics.loss_test/8_days/lc
metrics.loss_test/256_days/lc
metrics.loss_validation/tab_ce
metrics.loss_train/tab_entropy
metrics.loss_test/128_days/tab_entropy
metrics.loss_test/16_days/mix_entropy
metrics.loss_test/None_days/lc
metrics.mix/f1s_train_step
metrics.mix/rcl_test/256_days
metrics.loss_train/total
metrics.loss_test/256_days/mix
metrics.loss_test/512_days/mix
metrics.mix/acc_test/64_days
metrics.loss_test/8_days/tab
metrics.loss_test/128_days/tab_ce
metrics.loss_test/None_days/total
metrics.loss_test/256_days/tab
metrics.loss_test/256_days/tab_entropy
metrics.mix/acc_test/128_days
metrics.loss_test/8_days/lc_entropy
metrics.loss_train/tab
metrics.loss_test/128_days/lc
metrics.loss_test/8_days/lc_ce
metrics.loss_test/1024_days/lc_ce
metrics.mix/rcl_train_step
metrics.loss_train/tab_ce
metrics.mix/acc_test/None_days
metrics.loss_test/1024_days/total
metrics.loss_test/1024_days/lc
metrics.loss_validation/tab_entropy
metrics.loss_test/8_days/tab_entropy
metrics.mix/acc_train_step
metrics.mix/rcl_test/128_days
metrics.loss_test/32_days/mix
metrics.loss_test/None_days/lc_ce
metrics.loss_test/None_days/tab_entropy
metrics.mix/f1s_test/512_days
metrics.loss_test/None_days/tab
metrics.loss_test/256_days/lc_ce
metrics.loss_train/lc_entropy
metrics.loss_test/1024_days/tab
metrics.loss_test/512_days/lc_ce
metrics.loss_test/256_days/mix_ce
metrics.loss_validation/mix_entropy
metrics.loss_validation/tab
metrics.mix/acc_valid
metrics.loss_test/128_days/mix_entropy
metrics.loss_test/None_days/mix_ce
metrics.loss_test/64_days/tab_ce
metrics.loss_test/None_days/lc_entropy
metrics.loss_test/32_days/tab_entropy
metrics.loss_test/32_days/mix_entropy
metrics.loss_test/8_days/mix
metrics.mix/f1s_valid
metrics.loss_test/64_days/lc_entropy
metrics.epoch
metrics.loss_test/1024_days/tab_ce
metrics.mix/f1s_train_epoch
metrics.loss_test/512_days/lc
metrics.mix/f1s_test/1024_days
metrics.loss_test/512_days/lc_entropy
metrics.loss_test/None_days/mix
metrics.loss_test/None_days/mix_entropy
metrics.loss_test/512_days/tab_ce
metrics.loss_train/lc
metrics.loss_test/64_days/mix_entropy
metrics.mix/rcl_test/512_days
metrics.mix/acc_test/1024_days
metrics.loss_train/mix
metrics.loss_test/128_days/lc_entropy
metrics.loss_validation/lc
metrics.mix/acc_train_epoch
metrics.mix/acc_test/256_days
metrics.mix/f1s_test/8_days
metrics.loss_test/16_days/lc_entropy
metrics.mix/rcl_test/16_days
metrics.loss_test/128_days/lc_ce
metrics.loss_test/None_days/tab_ce
metrics.loss_test/16_days/lc
metrics.loss_test/64_days/total
metrics.loss_test/64_days/lc_ce
metrics.mix/f1s_test/128_days
metrics.loss_train/mix_entropy
metrics.loss_test/64_days/mix
metrics.loss_validation/lc_entropy
metrics.loss_test/16_days/mix
metrics.loss_test/16_days/lc_ce
metrics.mix/acc_test/8_days
metrics.loss_test/32_days/total
metrics.loss_validation/mix_ce
metrics.loss_test/32_days/tab_ce
metrics.loss_test/512_days/mix_ce
metrics.mix/rcl_test/32_days
metrics.loss_test/16_days/tab
metrics.loss_test/64_days/lc
metrics.lr-Adam
metrics.mix/f1s_test/32_days
metrics.loss_test/256_days/mix_entropy
metrics.mix/f1s_test/256_days
metrics.loss_test/512_days/total
metrics.loss_test/64_days/tab
metrics.loss_validation/lc_ce
metrics.loss_test/256_days/total
metrics.loss_test/64_days/tab_entropy
params.lc/encoder_type
params.general/use_only_det
params.general/force_online_opt
params.general/use_augmented_dataset
params.general/name_dataset
params.general/norm_type
params.general/use_QT
params.general/use_mask_detection
params.lc/input_size
params.general/src_checkpoint
params.general/debug
params.general/online_opt_tt
params.ft/encoder_type
params.general/use_lightcurves
params.lc/cnn_kernel
params.lc/num_bands
params.general/change_clf
params.lc/embedding_size
params.general/batch_size
params.general/lr
params.lc/num_harmonics
params.general/num_epochs
params.general/label_smoothing
params.general/num_classes
params.general/fold
params.ft/embedding_size
params.general/is_searching_hyperparameters
params.general/top_n_feats
params.general/use_gradient_clipping
params.general/qt_type
params.general/list_time_to_eval
params.ft/num_encoders
params.general/experiment_name
params.lc/pe_type
params.lc/num_heads
params.ft/length_size
params.general/experiment_phase
params.general/patience
params.ft/num_heads
params.general/experiment_type
params.lc/max_pool_kernel
params.general/entropy_beta
params.lc/use_emb_x_band
params.lc/embedding_size_sub
params.general/use_cosine_decay
params.general/use_time_nondetection
params.general/use_features
params.lc/Tmax
params.general/data_root
params.general/use_metadata
params.general/use_lightcurves_err
params.ft/embedding_size_sub
params.general/load_pretrained_model
params.lc/num_encoders
tags.mlflow.parentRunId
tags.mlflow.source.name
tags.mlflow.runName
tags.mlflow.source.type
tags.mlflow.user
tags.mlflow.source.git.commit

In [24]:
# Asumiendo que tienes un Series llamado 'trials_series'
trials_series_sorted = runs['params.general/experiment_name'].value_counts().sort_index(
    key=lambda x: x.str.extract(r'(\d+)').astype(int).squeeze()
)

print(trials_series_sorted)

params.general/experiment_name
trial_0     5
trial_1     5
trial_2     5
trial_3     5
trial_4     5
trial_5     5
trial_6     5
trial_7     5
trial_8     5
trial_9     5
trial_10    5
trial_11    5
trial_12    5
trial_13    5
trial_14    5
trial_15    5
trial_16    5
trial_17    5
Name: count, dtype: int64

In [31]:
columns_hp = [
    'params.lc/num_encoders', 'params.lc/embedding_size', 'params.lc/embedding_size_sub',
    'params.ft/num_encoders', 'params.ft/embedding_size', 'params.ft/embedding_size_sub',
    'params.general/use_lightcurves_err'
    ]

In [32]:
fold_run = {run_id: (fold, exp_name) for run_id, fold, exp_name in zip(
    runs['run_id'], runs['params.general/fold'], runs['params.general/experiment_name']
    )}
fold_run

{'f46a3101b3fe435badd1e18d5d5880d5': ('4', 'trial_17'),
 'c5aed04a7df34c63afc04184625da973': ('3', 'trial_17'),
 '66f68d85b4bf4ea38280701373aace94': ('4', 'trial_16'),
 '875f250a750e4967909d33fd480e2cd8': ('2', 'trial_17'),
 '30cd423d063e4062b329fb48d85d369c': ('4', 'trial_15'),
 '9ff50f6ca4d741908a8ef278640fc170': ('1', 'trial_17'),
 '8adecb415325419096fa2a69abfce116': ('3', 'trial_16'),
 '6900a46add4b4e26a46a714cda5411e2': ('3', 'trial_15'),
 'e1bf003bc601450d81afe62bc9b05f3c': ('0', 'trial_17'),
 '0c83788e79094cb9a2c8898475a87b43': ('2', 'trial_16'),
 '63067c6823554f1196b04fad1fbe8d2d': ('2', 'trial_15'),
 '9e0eb498eb8f401fb31c5f4aab5ab7e0': ('4', 'trial_2'),
 '5000a0ec65da4100b0a6453e6df3ca87': ('3', 'trial_2'),
 '01e460cd659047309f55d57db1fca493': ('2', 'trial_2'),
 '596842c4cd374ae6908f3586a5da9399': ('1', 'trial_16'),
 'dcc0b1d3a51b4bd8992cd3b3d59bf87b': ('1', 'trial_15'),
 '102680df55ec42ffb6dfaf013cbdbb56': ('1', 'trial_2'),
 '88cad1c4aa2a415db69891fcb14fb44f': ('0', 'trial_16'),
 '07461ddae0ae4b5ab1fc13c5f79a7f95': ('0', 'trial_15'),
 '6d0f20ad1cec42a99fcef7575e1e7749': ('0', 'trial_2'),
 '4f837370ab3544898fbe7c87121f19ed': ('4', 'trial_7'),
 '6342f2e83588410fa0869aba7cba31d4': ('4', 'trial_14'),
 '7ef6bade8b3746dfa519c7dc9dae873c': ('3', 'trial_14'),
 '7975bb304e2846c28fd228c219bf703b': ('2', 'trial_14'),
 '381b8a20db28447aa4fdbfe3baf106de': ('4', 'trial_13'),
 '3a30038700084b9c807868c7a72ace46': ('1', 'trial_14'),
 'c5864d848c2343569439fbe0dc231b9b': ('0', 'trial_14'),
 'f9f43f2fd4fe4dc0ad4a4791617c90a7': ('3', 'trial_7'),
 '1269b0dbb99c435da0f523ab49f9d655': ('4', 'trial_8'),
 '195001dd0ea049ed8f1ba52a302fe8be': ('4', 'trial_12'),
 'c121e9dc075e46909295fd20d2ce56c1': ('3', 'trial_13'),
 '87aba3e0138249c4bbf5ffb062ec1763': ('3', 'trial_12'),
 '2369e1bce6e74b33ad960769fd74e41d': ('3', 'trial_8'),
 'f183b47b591f49b8a5dda36d93aee412': ('4', 'trial_6'),
 'd7f3e11adfbc48d7b3ad522d6416f95c': ('2', 'trial_13'),
 '130c48351dd746c58a905eef67ab2a1a': ('2', 'trial_8'),
 '052d85224f67417ea78211e6348cda99': ('2', 'trial_7'),
 'fcdacfbfb4b942e995542e6abd3c2386': ('2', 'trial_12'),
 'e6f535ed670842fd86fb6342797f7096': ('1', 'trial_13'),
 '9489d3bf2da645ddade3f62acd5e7b6b': ('3', 'trial_6'),
 '7cb73d7306ba48b9ae71ce7a17605468': ('1', 'trial_12'),
 '1d30a2bc279548e9a9f16032482500c6': ('0', 'trial_13'),
 '72c54eaf477947869b160ac1559aae84': ('0', 'trial_12'),
 'c5d83ff5f85a484facf4486ad7353cc8': ('1', 'trial_8'),
 '0c58f883647d4e4ab9012fe1533f3d17': ('1', 'trial_7'),
 '4731f940fc23457387eedccfd6543282': ('2', 'trial_6'),
 'c0d18f571f104048aae57284eacc9da4': ('4', 'trial_11'),
 'a50d64ffb7c847f7afb814b05a626c20': ('3', 'trial_11'),
 'a4b4a96f7a814117bc7562b17790eed0': ('1', 'trial_6'),
 'e6bf2a4cdc584768aadf73621ded1a36': ('2', 'trial_11'),
 'e37ac1eac3f9479da04cebe0248704a7': ('1', 'trial_11'),
 '8a9a0c659ddf4427ad7e05eefc2898ad': ('0', 'trial_8'),
 'd5c19bbf8354440f88028ee07a42b341': ('0', 'trial_7'),
 '58a64569b0a2477d8deeab311e7efc57': ('0', 'trial_6'),
 '05de6a17a99b43ea92f5d86016abcb39': ('0', 'trial_11'),
 '5849b73220854c1cbe523ac6960f59d8': ('4', 'trial_9'),
 '425311b483844f87b1a3f374cc907509': ('3', 'trial_9'),
 '25a067327cb84a75a59f540f888d20c7': ('4', 'trial_1'),
 'e99c1343798046979d0c73e17abda8b9': ('2', 'trial_9'),
 '07b8eb049b68475691da775cd5ab0df7': ('3', 'trial_1'),
 '90f2a0f55f294969abd21f1b0d0ecaed': ('4', 'trial_10'),
 '806fd26e17574c2f880442ab26d1afaf': ('4', 'trial_4'),
 '0187513c0679455995c97c0740ae0c31': ('3', 'trial_10'),
 '0055116882ac4b41ab704a2cd5c263bf': ('4', 'trial_0'),
 '564d1055cfd84a21b539e1dcda7572b3': ('4', 'trial_3'),
 '7df85b026f6342d18ca6225ea468c36e': ('4', 'trial_5'),
 '80dae10525e04a7bbe299a60e52d3292': ('2', 'trial_1'),
 'c8a5c580f07a460595518e0eb3c6e65c': ('3', 'trial_4'),
 'eebaf18e494d4efabbd11d68986982a2': ('1', 'trial_9'),
 'e635aa4f499941ecbb87b4b42489683b': ('2', 'trial_10'),
 'f0ace43b6b7841d98afdf39504f1c30f': ('3', 'trial_5'),
 '4fa73744da4342978e7c0e435df2b271': ('3', 'trial_0'),
 '59d456b253174eeb896c0c4d61067b41': ('2', 'trial_4'),
 '1394cf33b7454b3198f51baf94bdcae2': ('3', 'trial_3'),
 '3d5234087da148eea5c8857353dde2a1': ('2', 'trial_5'),
 '7188cdedadea4bdab6cde2bfb8e55055': ('1', 'trial_10'),
 'f7e3ba6d48094adeb53409e484bf39c5': ('1', 'trial_1'),
 '8eddb8c22f464f76b0139cfc52bfd875': ('1', 'trial_4'),
 '05ce0664cc954364b24be2f2b76f4e56': ('2', 'trial_0'),
 '9636be3ec0c8497aac5d3762fb6774ac': ('1', 'trial_5'),
 '7ae339d761684cffa48ca763901126b8': ('0', 'trial_10'),
 'a2446bb6c39e471fa0d2a96b36e0b859': ('0', 'trial_9'),
 '843974863f7548b4ab68e00aa501b61a': ('0', 'trial_5'),
 'b240a42049b24b49b3bb82eddcbce494': ('0', 'trial_4'),
 '7dce15a4bdab4529a8f6e5b4a4f0efd6': ('0', 'trial_1'),
 'dcdad0b40a8749ca90d2ad74214a9ae0': ('2', 'trial_3'),
 '0d04a07a886740128afdf10d1a308e2e': ('1', 'trial_0'),
 '51616c2dbfdd4a5d8553bf3ddef24b98': ('1', 'trial_3'),
 'f99d2c29ea434572bba74deec8ea91ed': ('0', 'trial_3'),
 '0c6b82455f974a2abfb0b1c757c0bbe4': ('0', 'trial_0')}

In [33]:
import numpy as np

# Diccionario para almacenar las métricas por exp_name
metrics = {}

for run_id, (fold, exp_name) in fold_run.items():
    # Cargar predicciones
    path_clf_report = f'../models/ATAT/results/ml-runs/{experiment_id}/{run_id}/artifacts'
    atat_df_predictions = pd.read_parquet(f'{path_clf_report}/predictions_test.parquet').set_index('id')
    y_test = atat_df_predictions['y_true'].values
    atat_y_pred = atat_df_predictions['y_pred'].values
    
    # Calcular el reporte de clasificación
    report_atat = classification_report(y_test, atat_y_pred, output_dict=True)
    macro_precision = report_atat['macro avg']['precision']
    macro_recall = report_atat['macro avg']['recall']
    macro_f1 = report_atat['macro avg']['f1-score']

    hp_values = [runs[runs.run_id == run_id][col].values[0] for col in columns_hp]
    
    # Guardar los valores en la lista correspondiente a exp_name
    if exp_name not in metrics:
        metrics[exp_name] = {'precision': [], 'recall': [], 'f1-score': [], 'hp_values': []}
    metrics[exp_name]['precision'].append(macro_precision*100)
    metrics[exp_name]['recall'].append(macro_recall*100)
    metrics[exp_name]['f1-score'].append(macro_f1*100)
    metrics[exp_name]['hp_values'].append(hp_values)

# Crear DataFrame con los valores medios y desviaciones estándar
rows = []
for exp_name, values in metrics.items():
    row_macro = [exp_name]
    row_macro.extend([
        f"{np.mean(values['precision']):.2f} ± {np.std(values['precision']):.2f}",
        f"{np.mean(values['recall']):.2f} ± {np.std(values['recall']):.2f}",
        f"{np.mean(values['f1-score']):.2f} ± {np.std(values['f1-score']):.2f}"
    ])
    row_macro.extend(values['hp_values'][0])
    rows.append(row_macro)

# Crear DataFrame
columns = ['exp_name', 'macro_precision', 'macro_recall', 'macro_f1'] + columns_hp
report_macro_df = pd.DataFrame(rows, columns=columns).set_index('exp_name')
report_macro_df = report_macro_df.sort_values(by='macro_f1', ascending=False)
report_macro_df

,macro_precision,macro_recall,macro_f1,params.lc/num_encoders,params.lc/embedding_size,params.lc/embedding_size_sub,params.ft/num_encoders,params.ft/embedding_size,params.ft/embedding_size_sub,params.general/use_lightcurves_err
exp_name,,,,,,,,,,
trial_0,81.54 ± 0.69,78.78 ± 0.80,79.77 ± 0.63,2,96,192,2,64,128,False
trial_1,81.48 ± 1.01,78.45 ± 0.62,79.61 ± 0.67,2,96,192,3,128,256,False
trial_14,82.23 ± 0.75,77.95 ± 0.80,79.49 ± 0.66,3,192,384,4,256,512,True
trial_17,82.88 ± 0.95,77.66 ± 1.08,79.32 ± 0.69,4,384,768,4,256,512,True
trial_4,82.52 ± 1.04,77.42 ± 0.96,79.16 ± 1.07,3,192,384,3,128,256,False
trial_5,81.18 ± 0.74,78.00 ± 1.31,79.14 ± 1.09,3,192,384,4,256,512,False
trial_10,81.77 ± 0.44,77.82 ± 1.41,79.10 ± 1.05,2,96,192,3,128,256,True
trial_13,81.71 ± 0.77,77.67 ± 0.77,79.02 ± 0.62,3,192,384,3,128,256,True
trial_9,81.52 ± 0.98,77.66 ± 0.70,78.90 ± 0.87,2,96,192,2,64,128,True
trial_7,81.62 ± 0.65,77.09 ± 0.87,78.58 ± 0.80,4,384,768,3,128,256,False
trial_11,80.20 ± 0.85,77.56 ± 0.95,78.48 ± 0.65,2,96,192,4,256,512,True
trial_8,81.92 ± 1.18,76.82 ± 0.64,78.36 ± 0.59,4,384,768,4,256,512,False
trial_16,81.52 ± 0.87,76.56 ± 0.59,78.06 ± 0.57,4,384,768,3,128,256,True
trial_12,81.03 ± 1.21,76.59 ± 0.53,77.90 ± 0.67,3,192,384,2,64,128,True
trial_2,78.67 ± 0.47,77.38 ± 1.22,77.71 ± 0.90,2,96,192,4,256,512,False
trial_3,80.09 ± 2.03,76.31 ± 1.43,77.56 ± 1.61,3,192,384,2,64,128,False
trial_15,80.43 ± 1.63,75.34 ± 0.79,76.75 ± 0.64,4,384,768,2,64,128,True
trial_6,79.71 ± 1.12,74.06 ± 1.01,75.42 ± 0.96,4,384,768,2,64,128,False

## HBRF Hyperparameter Tuning

In [29]:
import pandas as pd

objects_partitions = pd.read_parquet('../data/partitions/250408_ndetge8/partitions.parquet')
objects_partitions

,oid,ra,dec,submitter,class_name,partition
28374,ZTF20aaznbxw,181.228246,3.565556,amunoz,RRLc,test
16896,ZTF19aasazxv,231.203476,34.986171,amunoz,QSO,test
32583,ZTF21aaizyqc,153.936939,43.096935,amunoz,SNII,test
13748,ZTF18aaavaza,159.020795,9.011837,amunoz,Periodic-Other,test
37952,ZTF18abyyhmt,99.998224,9.940071,amunoz,YSO,test
...,...,...,...,...,...,...
39460,ZTF17aaabgkn,83.392773,-4.729388,amunoz,YSO,validation_4
39466,ZTF21acqerum,309.341718,41.890336,amunoz,YSO,validation_4
39473,ZTF22aafamqx,246.671697,-22.002601,amunoz,YSO,validation_4
39476,ZTF22abudrqm,84.344000,-2.993351,amunoz,YSO,validation_4
39478,ZTF23aabvglf,70.269572,24.851789,amunoz,YSO,validation_4

In [30]:
import os
import numpy as np
import pandas as pd
import yaml
from sklearn.metrics import f1_score, classification_report

# Ruta base donde están los trials
parent_dir = "../models/HBRF/results/250408_ndetge8/HBRF_20251230-021343"

# Listar los trials
trials = sorted([d for d in os.listdir(parent_dir) if d.startswith("trial_")])

# Diccionario para almacenar las métricas por trial
metrics = {}

for trial in trials:
    trial_path = os.path.join(parent_dir, trial)
    
    # Cargar hiperparámetros del trial
    hparams_file = os.path.join(trial_path, "hparams.yaml")
    with open(hparams_file, "r") as file:
        hparams = yaml.safe_load(file)

    # Lista para almacenar los F1-scores de los folds de este trial
    precision_scores = []
    recall_scores = []
    f1_scores = []

    # Iterar sobre los folds dentro del trial
    folds = sorted([d for d in os.listdir(trial_path) if d.startswith("fold_")])
    for fold in folds:
        fold_path = os.path.join(trial_path, fold)
        pred_file = os.path.join(fold_path, "predictions_validation.parquet")

        partitions_val = objects_partitions[objects_partitions['partition'] == f'validation_{fold.split("_")[-1]}'].set_index('oid')
        y_val = partitions_val['class_name'].values

        if os.path.exists(pred_file):
            # Cargar predicciones
            hbrf_df_predictions = pd.read_parquet(pred_file)
            hbrf_df_predictions = hbrf_df_predictions[hbrf_df_predictions['shorten'] == 'None']
            hbrf_df_predictions.index = hbrf_df_predictions.index.astype(str).str.split('_').str[1]
            hbrf_df_predictions = hbrf_df_predictions.reindex(partitions_val.index) 
            hbrf_y_pred = hbrf_df_predictions['y_pred'].values

            # Calcular reporte de clasificación
            report = classification_report(y_val, hbrf_y_pred, output_dict=True)
            macro_precision = report['macro avg']['precision']
            macro_recall = report['macro avg']['recall']
            macro_f1 = report['macro avg']['f1-score']

            precision_scores.append(macro_precision * 100)
            recall_scores.append(macro_recall * 100)
            f1_scores.append(macro_f1 * 100)

    # Guardar los resultados en el diccionario
    if trial not in metrics:
        metrics[trial] = {'precision': [], 'recall': [], 'f1-score': [], 'hp_values': []}
    
    metrics[trial]['precision'].extend(precision_scores)
    metrics[trial]['recall'].extend(recall_scores)
    metrics[trial]['f1-score'].extend(f1_scores)
    metrics[trial]['hp_values'].append([hparams[key] for key in hparams if key not in ["mean_f1", "std_f1", "trial"]])

# Crear DataFrame con los valores medios y desviaciones estándar
rows = []
for trial, values in metrics.items():
    row = [trial]
    row.extend([
        f"{np.mean(values['precision']):.2f} ± {np.std(values['precision']):.2f}",
        f"{np.mean(values['recall']):.2f} ± {np.std(values['recall']):.2f}",
        f"{np.mean(values['f1-score']):.2f} ± {np.std(values['f1-score']):.2f}"
    ])
    row.extend(values['hp_values'][0])  # Asumiendo que los hiperparámetros son los mismos para todos los folds
    rows.append(row)

# Crear DataFrame final
columns_hp = list(hparams.keys())
columns = ['trial', 'macro_precision', 'macro_recall', 'macro_f1'] + columns_hp
report_macro_df = pd.DataFrame(rows, columns=columns).set_index('trial')
report_macro_df = report_macro_df.sort_values(by='macro_f1', ascending=False)
columns_to_remove = ['n_jobs', 'verbose']
report_macro_df = report_macro_df.drop(columns=[col for col in columns_to_remove if col in report_macro_df.columns], errors='ignore')
report_macro_df

,macro_precision,macro_recall,macro_f1,n_trees,criterion,max_depth
trial,,,,,,
trial_23,75.60 ± 0.91,79.06 ± 1.05,76.72 ± 1.01,500,entropy,NaN
trial_19,75.60 ± 0.91,79.06 ± 1.05,76.72 ± 1.01,500,gini,100.0
trial_20,75.60 ± 0.91,79.06 ± 1.05,76.72 ± 1.01,500,gini,NaN
trial_22,75.60 ± 0.91,79.06 ± 1.05,76.72 ± 1.01,500,entropy,100.0
trial_17,75.55 ± 1.01,79.04 ± 1.07,76.67 ± 1.08,350,entropy,NaN
trial_13,75.55 ± 1.01,79.04 ± 1.07,76.67 ± 1.08,350,gini,100.0
trial_14,75.55 ± 1.01,79.04 ± 1.07,76.67 ± 1.08,350,gini,NaN
trial_16,75.55 ± 1.01,79.04 ± 1.07,76.67 ± 1.08,350,entropy,100.0
trial_10,75.33 ± 0.65,78.99 ± 0.93,76.51 ± 0.76,100,entropy,100.0
trial_11,75.33 ± 0.65,78.99 ± 0.93,76.51 ± 0.76,100,entropy,NaN
trial_7,75.33 ± 0.65,78.99 ± 0.93,76.51 ± 0.76,100,gini,100.0
trial_8,75.33 ± 0.65,78.99 ± 0.93,76.51 ± 0.76,100,gini,NaN
trial_18,73.86 ± 0.66,77.85 ± 0.93,75.13 ± 0.71,500,gini,10.0
trial_21,73.86 ± 0.66,77.85 ± 0.93,75.13 ± 0.71,500,entropy,10.0
trial_12,73.41 ± 0.62,77.70 ± 0.99,74.75 ± 0.74,350,gini,10.0
trial_15,73.41 ± 0.62,77.70 ± 0.99,74.75 ± 0.74,350,entropy,10.0
trial_9,72.74 ± 0.83,76.98 ± 1.37,74.07 ± 1.05,100,entropy,10.0
trial_6,72.74 ± 0.83,76.98 ± 1.37,74.07 ± 1.05,100,gini,10.0
trial_5,69.27 ± 1.23,73.93 ± 1.53,70.48 ± 1.44,10,entropy,NaN
trial_2,69.27 ± 1.23,73.93 ± 1.53,70.48 ± 1.44,10,gini,NaN
trial_4,69.27 ± 1.23,73.93 ± 1.53,70.48 ± 1.44,10,entropy,100.0
trial_1,69.27 ± 1.23,73.93 ± 1.53,70.48 ± 1.44,10,gini,100.0
trial_0,68.13 ± 0.88,73.05 ± 1.09,69.43 ± 0.96,10,gini,10.0
trial_3,68.12 ± 0.88,73.04 ± 1.08,69.42 ± 0.95,10,entropy,10.0