In [2]:
%cd ../

/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin

In [4]:
import pandas as pd

In [8]:
stamps_real = pd.read_pickle('data/data_04122025/stamps_20251204.pickle')
stamps_real

,oid,measurement_id,flux_Science_data,flux_Science_header,flux_Template_data,flux_Template_header,flux_Difference_data,flux_Difference_header,variance_Science_data,variance_Science_header,...,mask_Science_header,mask_Template_data,mask_Template_header,mask_Difference_data,mask_Difference_header,level0_image,level1_image,level2_image,level3_image,level4_image
0,169298432645136566,169298432645136566,"[[-11.944677, 22.680063, 56.766247, -69.47594,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[12.199259, 13.337936, 4.610951, 12.187733, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-32.02772, -3.1861129, 29.517363, -62.336437...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2029.274, 2043.5964, 2039.1626, 1984.181, 20...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.10...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.02065728, 0.02685283, 0.031547748, 0.03359...","[[0.000107888554, 0.0010335624, 0.00073960784,...","[[0.0008051935, 0.0010344381, 0.00048950204, 0...","[[-1.5311905e-05, -6.66794e-05, 5.857322e-05, ...","[[0.0003843297, 2.6904874e-05, 0.00012262391, ..."
1,169298432645136566,169342390804939401,"[[33.749435, 4.7337646, -4.1696296, 26.699196,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.1481447, 8.424211, 7.827461, 11.172089, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[27.152315, -2.5955675, -13.17436, 17.591114,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[113.52766, 100.46256, 97.016266, 111.73376, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.19...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.02065728, 0.02685283, 0.031547748, 0.03359...","[[0.000107888554, 0.0010335624, 0.00073960784,...","[[0.0008051935, 0.0010344381, 0.00048950204, 0...","[[-1.5311905e-05, -6.66794e-05, 5.857322e-05, ...","[[0.0003843297, 2.6904874e-05, 0.00012262391, ..."
2,169298432645136566,169342391077569156,"[[14.1986685, 16.078861, 26.577322, 12.6218405...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[9.341842, 6.657908, 11.416469, 18.659191, 14...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[1.8367354, 2.7625208, 12.323781, -1.4950584,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[106.31643, 106.894806, 111.61526, 106.38621,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 7.1...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.02065728, 0.02685283, 0.031547748, 0.03359...","[[0.000107888554, 0.0010335624, 0.00073960784,...","[[0.0008051935, 0.0010344381, 0.00048950204, 0...","[[-1.5311905e-05, -6.66794e-05, 5.857322e-05, ...","[[0.0003843297, 2.6904874e-05, 0.00012262391, ..."
3,169298432645136566,169342391901225029,"[[6.0203543, 19.228369, 14.368738, 2.777589, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[19.613558, 14.605038, 14.2760315, 14.001043,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-5.926975, 9.273454, 0.7756388, -10.462706, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[98.41768, 104.779945, 101.48598, 96.247055, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.40...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.02065728, 0.02685283, 0.031547748, 0.03359...","[[0.000107888554, 0.0010335624, 0.00073960784,...","[[0.0008051935, 0.0010344381, 0.00048950204, 0...","[[-1.5311905e-05, -6.66794e-05, 5.857322e-05, ...","[[0.0003843297, 2.6904874e-05, 0.00012262391, ..."
4,169298436562092346,169298436562092346,"[[nan, 31.483622, 31.467676, 67.88891, 106.513...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[138.97568, 156.42183, 169.49625, 187.52122, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[nan, -123.2008, -135.09485, -112.910324, -92...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[inf, 2145.6533, 2145.6533, 2205.3682, 2269.2...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.06...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.023195267, 0.025125092, 0.027328428, 0.028...","[[0.0053146053, 0.005690865, 0.0074089626, 0.0...","[[0.001371908, 0.00057243503, 0.001549511, 0.0...","[[6.234929e-05, 0.00026754188, -0.00017663867,...","[[0.00038373444, 0.0011057648, 0.0005601042, -..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,169623885986660770,169623885986660770,"[[34.29998, -1.3532993, 36.94331, -6.6487756, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-1.0223907, -1.3383079, 2.3625648, -1.023431...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[34.600986, -1.6656876, 34.48847, -6.5335402,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[496.43213, 479.12585, 504.6476, 472.31485, 4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.59...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[-0.000427846, -0.0005762525, 9.029108e-05, 0...","[[-0.00014843051, 0.00065468985, 0.0002319735,...","[[-5.7443162e-06, 0.0001243852, 0.0002680619, ...","[[0.0005500209, 0.0036284153, 0.0017915394, 0....","[[-9.6716976e-05, -0.00010848437, -0.000188904..."
95,169623886050099223,169623886050099223,"[[1.8700596, 6.320598, -1.3027842, 18.03109, 1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[3.607972, 12.782658, 4.041826, 2.294311, 8.1...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[2.147793, 9.802163, -2.882767, 24.878992, 20...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[416.88007, 420.5753, 415.79083, 426.0246, 42...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.01...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[-0.0011528156, 0.00018901602, 0.0007678549, ...","[[0.00035051786, 0.0004195475, -0.00015346851,...","[[-5.463161e-05, -0.00031676542, -0.0001100024...","[[0.00018370915, -1.3363477e-05, 0.00021883413...","[[0.0001950424, 9.002396e-06, 3.2414435e-05, 1..."
96,169623886051672110,169623886051672110,"[[57.805122, 44.79508, 33.876152, 31.120367, 8...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[23.34773, 37.00166, 50.152416, 54.62792, 77....","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[34.330482, 16.481386, -9.456376, -28.318365,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[464.6502, 447.46368, 442.83194, 442.03995, 4...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.53...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[-0.00031757125, 0.0006127976, 0.0006479019, ...","[[-0.0003902635, 0.00023095218, 8.7872395e-05,...","[[-0.0004067194, -0.00017256329, -0.0002451450...","[[0.00017392078, -7.316567e-05, -0.00023379848...","[[0.001138993, 0.00032527815, 0.00015816069, 0..."
97,169623886096236648,169623886096236648,"[[-26.230595, 21.359947, 1.6237268, -13.303078...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[16.963127, 20.906433, 19.918447, 17.486729, ...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-36.786396, 8.652391, -14.986927, -30.314152...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[382.40063, 414.28006, 401.82614, 390.58652, ...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -8.5...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[-0.000107847176, 0.00037816024, 0.0012595754...","[[0.00015823667, 0.0003811099, 0.00023235458, ...","[[0.00033449876, 0.0004913145, 0.0014061499, 0...","[[-8.512894e-05, 0.00018973142, 0.0026873522, ...","[[0.00012513835, -0.00013499668, 9.387207e-05,..."
98,169623886116683891,169623886116683891,"[[1.0994717, 8.838287, -13.394072, -18.971634,...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-0.85564506, 6.282042, 1.0400512, -2.4211469...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[-9.51214, 2.1227539, -30.30768, -19.58929, 2...","[SIMPLE, BITPIX, NAXIS, NAXIS1, NAXIS2, EXTEND...","[[498.15924, 506.37625, 487.9658, 489.0806, 50...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...",...,"[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.83...","[XTENSION, BITPIX, NAXIS, NAXIS1, NAXIS2, PCOU...","[[-7.1065304e-05, -0.00023749992, 0.0001675270...","[[-0.00024103865, 2.3850864e-05, 1.0147941e-05...","[[-9.008784e-05, 0.00016025656, -0.00020440467...","[[0.00021522396, -0.0001678439, -0.00012674862...","[[0.00022831911, 7.7103774e-05, 0.00044052416,..."

In [9]:
partitions_real = pd.read_csv('data/data_04122025/folds_20251204.csv')
partitions_real

                      oid      measurement_id     cl   fold
0      169298437874909259  169298437874909259    AGN   test
1      169302853217681420  169302853217681420    AGN   test
2      169302853217681420  169342394726088762    AGN   test
3      169302854308200461  169302854308200461    AGN   test
4      169302854308200461  169342391330275400    AGN   test
...                   ...                 ...    ...    ...
33639  169606292775109159  169606292775109159  bogus  val_4
33640  169606292811284529  169606292811284529  bogus  val_4
33641  169615110258032702  169615110258032702  bogus  val_4
33642  169623886050099223  169623886050099223  bogus  val_4
33643  169623886096236648  169623886096236648  bogus  val_4

[33644 rows x 4 columns]

In [10]:
conteo = partitions_real.groupby(['fold', 'cl']).size().reset_index(name='count')
conteo_pivot = conteo.pivot(index='fold', columns='cl', values='count').fillna(0)
print(conteo_pivot)

cl        AGN   SN   VS  asteroid  bogus
fold
test      186   35  178       401    424
train_0  1680  163  770      1477   1384
train_1  1672  162  773      1482   1398
train_2  1673  172  776      1474   1387
train_3  1676  164  772      1509   1392
train_4  1667  166  771      1486   1385
val_0     109   19  150       380    352
val_1     117   20  147       375    338
val_2     116   10  144       383    349
val_3     113   18  148       348    344
val_4     122   16  149       371    351